name: whsun-docs
channels:
  - defaults
dependencies:
  - python
  - pip
  - pip:
      - mkdocs-material
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-git-committers-plugin-2
      - mkdocs-glightbox